### ISSUE TITLE
Doesnt work with Android 9

### ISSUE THREAD

**Issue by Kolyall** [centic9/poi-on-android#87] opened 2020-10-15 14:13 UTC
TargetSdkVersion = 28, CompileSdkVersion = 28
device: Android 9

Input file is "myfile.xlsx"
```
val workbook = XSSFWorkbook(file.absolutePath)
val outputStream = FileOutputStream(file.absolutePath) 
workbook.write(outputStream)
outputStream.close()
workbook.close()

```
Crashes with error:
```
A/libc: Fatal signal 7 (SIGBUS), code 2 (BUS_ADRERR), fault addr 0xea862b86
```
By debug it failed on this line:
```
org.apache.poi.POIXMLProperties:: line 46
```

**Comment by centic9** [comment] 2022-01-31 06:22
Crashes like this indicate some lower-level problem than pure Java code. You can check system logs at that time to see if there were any related issues on the operation-system. Other than that I don't know enough about Android development to be able to help further, sorry.

**Comment by centic9** [comment] 2022-02-08 10:55
Could not reproduce this, so closing for now, in the meantime the project uses SDKVersion 32 without such an issue being reported.

Please reopen this if you still experience this with the latest version, ideally with a small app that allows to easily reproduce this problem.

**Closed** 2022-03-21 19:13 UTC
