### ISSUE TITLE
crash in createHelper.createHyperlink(Hyperlink.LINK_URL)

### ISSUE THREAD

**Issue by jacky-1** [centic9/poi-on-android#20] opened 2017-08-06 15:22 UTC
Hi,
First of all, thanks for sharing! 
I'm able to use your poishadow-all.jar ver 0.5 to create nice excel files..
Unfortunately I'm getting the following crash when executing the instruction line:
Hyperlink link = createHelper.createHyperlink(Hyperlink.LINK_URL);
Stack trace:
08-06 17:23:50.438 17495-19724/? W/System.err: java.lang.ClassCastException: org.apache.xmlbeans.impl.g.au cannot be cast to org.openxmlformats.schemas.spreadsheetml.x2006.main.u
08-06 17:23:50.438 17495-19724/? W/System.err:     at org.openxmlformats.schemas.spreadsheetml.x2006.main.u$a.a(Unknown Source)
08-06 17:23:50.438 17495-19724/? W/System.err:     at org.apache.a.h.b.y.<init>(SourceFile:60)
08-06 17:23:50.438 17495-19724/? W/System.err:     at org.apache.a.h.b.y.<init>(SourceFile:49)
08-06 17:23:50.439 17495-19724/? W/System.err:     at org.apache.a.h.b.o.b(SourceFile:69)
08-06 17:23:50.439 17495-19724/? W/System.err:     at org.apache.a.h.b.o.a(SourceFile:26)
-------------------------------------------------------
the relevant code for creating the hyperlink in a cell:
CreationHelper createHelper = workbook.getCreationHelper();
cell.setCellValue("click here");
Hyperlink link = createHelper.createHyperlink(Hyperlink.LINK_URL);
link.setAddress("https://www.google.com");
cell.setHyperlink(link);

Thanks

**Comment by jacky-1** [comment] 2017-08-11 20:12
This issue is solved by adding the proguard rule lines from issue #18 
-keep class org.openxmlformats.schemas.spreadsheetml.x2006.main** { *; }
-keep class org.openxmlformats.schemas.spreadsheetml.x2006.main.impl** { *; }

**Comment by centic9** [comment] 2017-08-23 14:20
I tried to reproduce this, but could not with the latest version, I have now added similar code to the test-application and there it works (at least in the Emulator, didn't try in the real device, but I doubt it is related).

**Comment by centic9** [comment] 2018-03-17 21:07
No answer for some time and I could not reproduce it with the current version, therefore I am closing this now. Please reopen or create new issues if it still does not work for you.

**Closed by centic9** 2018-03-17 21:07 UTC
