### ISSUE TITLE
Error in POIMetadataExtracter 

### ISSUE THREAD

**Issue by Harmeet2491** [centic9/poi-on-android#15] opened 2017-07-10 19:34 UTC
Adding properties to activity:
System.setProperty("org.apache.poi.javax.xml.stream.XMLInputFactory","com.fasterxml.aalto.stax.InputFactoryImpl");
System.setProperty("org.apache.poi.javax.xml.stream.XMLOutputFactory","com.fasterxml.aalto.stax.OutputFactoryImpl");System.setProperty("org.apache.poi.javax.xml.stream.XMLEventFactory", "com.fasterxml.aalto.stax.EventFactoryImpl");
Causes error: org.apache.xmlbeans.SchemaTypeLoaderException: Cannot resolve type for handle _XY_Q=space|R=space@http://www.w3.org/XML/1998/namespace (schemaorg_apache_xmlbeans.system.sF1327CCA741569E70F9CA8C9AF9B44B2.cttext7f5btype) - code 13

**Comment by centic9** [comment] 2017-07-10 20:55
This is a duplicate of issue #13.

**Closed by centic9** 2017-07-10 20:55 UTC
